swagger: '2.0'
info:
  description: >-
    API and services that support the consumption of consumer-facing resources
    such as product reviews, snippets, questions, and answers.
  version: 1.0.0
  title: Read Services
  termsOfService: 'http://www.powerreviews.com/terms-of-use/'
host: readservices-b2c.powerreviews.com
basePath: /
tags:
  - name: Reviews
    description: Endpoints for product reviews by merchant
  - name: Q&A
    description: Endpoints for product questions and answers by merchant
  - name: Snippets
    description: Endpoints for product snippets by merchant
  - name: Configuration 
    description: Endpoints for merchant configuration
paths:
  '/m/{merchantId}/l/{locale}/product/{pageIds}/snippet':
    get:
      tags:
        - Snippets
      summary: getProductSnippets
      operationId: getProductSnippetsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: apikey
          in: query
          required: true
          type: string
        - name: merchantId
          in: path
          required: true
          type: string
        - name: locale
          in: path
          required: true
          type: string
        - name: pageIds
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/QueryResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/m/{merchantId}/l/{locale}/product/{pageId}/questions':
    get:
      tags:
        - Q&A
      summary: getQuestions
      operationId: getQuestionsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: paging.size
          in: query
          required: false
          type: integer
          format: int32
        - name: paging.from
          in: query
          required: false
          type: integer
          format: int32
        - name: sort
          in: query
          required: false
          type: string
          enum:
            - Oldest
            - Newest
            - MostAnswers
        - name: apikey
          in: query
          required: false
          type: string
        - name: merchantId
          in: path
          required: true
          type: string
        - name: locale
          in: path
          required: true
          type: string
        - name: pageId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/QueryResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/m/{merchantId}/l/{locale}/product/{pageId}/reviews':
    get:
      tags:
        - Reviews
      summary: getProductReviews
      operationId: getProductReviewsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: paging.size
          in: query
          required: false
          type: integer
          format: int32
        - name: paging.from
          in: query
          required: false
          type: integer
          format: int32
        - name: sort
          in: query
          required: false
          type: string
          enum:
            - HighestRating
            - LowestRating
            - MostHelpful
            - Oldest
            - Newest
        - name: apikey
          in: query
          required: true
          type: string
        - name: merchantId
          in: path
          required: true
          type: string
        - name: locale
          in: path
          required: true
          type: string
        - name: pageId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/QueryResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/m/{merchantId}/l/{locale}/question/{questionId}/answers':
    get:
      tags:
        - Q&A
      summary: getAnswers
      operationId: getAnswersUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: paging.size
          in: query
          required: false
          type: integer
          format: int32
        - name: paging.from
          in: query
          required: false
          type: integer
          format: int32
        - name: apikey
          in: query
          required: false
          type: string
        - name: merchantId
          in: path
          required: true
          type: string
        - name: locale
          in: path
          required: true
          type: string
        - name: questionId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/QueryResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/m/{merchant_id}/l/{locale}/configuration':
    get:
      tags:
        - Configuration
      summary: getConfigurationByMerchant
      operationId: getConfigurationByMerchantUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: merchant_id
          in: path
          description: merchant_id
          required: true
          type: integer
          format: int64
        - name: locale
          in: path
          description: locale
          required: true
          type: string
        - name: apikey
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ConfigurationResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  ConfigurationResponse:
    type: object
    properties:
      features:
        type: object
        additionalProperties:
          type: array
          items:
            type: string
      localizations:
        type: object
        additionalProperties:
          type: string
      properties:
        type: object
  PagingResponse:
    type: object
    properties:
      current_page_number:
        type: integer
        format: int32
      next_page_url:
        type: string
      page_size:
        type: integer
        format: int32
      pages_total:
        type: integer
        format: int64
      total_results:
        type: integer
        format: int64
  QueryResponse:
    type: object
    properties:
      configuration:
        $ref: '#/definitions/ConfigurationResponse'
      name:
        type: string
        enum:
          - snippet
          - review
          - questions
          - answers
      paging:
        $ref: '#/definitions/PagingResponse'
      results:
        type: array
        items:
          type: object
