on: push
name: deploy help site
jobs:
  is-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: is-master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: deploy
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 sync . s3://developers.powerreviews.com/ --storage-class REDUCED_REDUNDANCY
          --delete
